import test from "node:test";
import assert from "node:assert/strict";
import { decodeBmp24, trackPoint } from "../.tmp/runtime/packages/tracking/src/index.js";

const frame=(width,height,target)=>{const rgb=new Uint8Array(width*height*3);for(let y=0;y<height;y++)for(let x=0;x<width;x++){const o=(y*width+x)*3;const noise=(x*17+y*29+(x*y)%31)%43;rgb[o]=12+noise;rgb[o+1]=18+(noise*2)%37;rgb[o+2]=28+(noise*3)%53}for(let dy=-4;dy<=4;dy++)for(let dx=-4;dx<=4;dx++){const x=target.x+dx,y=target.y+dy,o=(y*width+x)*3;const mark=(dx===0||dy===0||dx===dy)?240:70;rgb[o]=mark;rgb[o+1]=(dx===0?248:90);rgb[o+2]=(dy===0?250:55)}return{width,height,rgb}};
const bmp24=(image)=>{const stride=Math.ceil(image.width*3/4)*4,b=Buffer.alloc(54+stride*image.height);b.write("BM",0,2,"ascii");b.writeUInt32LE(b.length,2);b.writeUInt32LE(54,10);b.writeUInt32LE(40,14);b.writeInt32LE(image.width,18);b.writeInt32LE(image.height,22);b.writeUInt16LE(1,26);b.writeUInt16LE(24,28);b.writeUInt32LE(stride*image.height,34);for(let y=0;y<image.height;y++)for(let x=0;x<image.width;x++){const s=(y*image.width+x)*3,d=54+(image.height-1-y)*stride+x*3;b[d]=image.rgb[s+2];b[d+1]=image.rgb[s+1];b[d+2]=image.rgb[s]}return b};

test("point tracker derives motion from pixels rather than supplied ground truth",()=>{const truth=[{x:26,y:28},{x:31,y:30},{x:37,y:34},{x:44,y:37},{x:50,y:42},{x:57,y:45}];const frames=truth.map(p=>frame(96,72,p));const result=trackPoint({frames,seed:truth[0],featureRadius:4,searchRadius:10,minSimilarity:0.7,minSeparation:0.002});assert.equal(result.status,"TRACKED");assert.deepEqual(result.samples.map(s=>s.point),truth);assert.ok(result.samples.slice(1).every(s=>s.similarity>0.7&&s.separation>0.002));});

test("24-bit BMP decoder preserves tracker coordinates",()=>{const truth=[{x:24,y:25},{x:29,y:29},{x:35,y:32}];const decoded=truth.map(p=>decodeBmp24(bmp24(frame(80,60,p))));const result=trackPoint({frames:decoded,seed:truth[0],featureRadius:4,searchRadius:9,minSimilarity:0.7,minSeparation:0.002});assert.equal(result.status,"TRACKED");assert.deepEqual(result.samples.map(s=>s.point),truth);});

test("point tracker fails closed when the search result is ambiguous",()=>{const first=frame(64,48,{x:20,y:24});const second={width:64,height:48,rgb:new Uint8Array(first.rgb.length)};for(let i=0;i<second.rgb.length;i++)second.rgb[i]=30;const patch=(cx)=>{for(let dy=-4;dy<=4;dy++)for(let dx=-4;dx<=4;dx++){const s=((24+dy)*64+(20+dx))*3,d=((24+dy)*64+(cx+dx))*3;second.rgb[d]=first.rgb[s];second.rgb[d+1]=first.rgb[s+1];second.rgb[d+2]=first.rgb[s+2]}};patch(17);patch(23);const result=trackPoint({frames:[first,second],seed:{x:20,y:24},featureRadius:4,searchRadius:8,minSimilarity:0.7,minSeparation:0.01});assert.equal(result.status,"REJECTED");assert.equal(result.rejectedFrameIndex,1);assert.equal(result.reason,"AMBIGUOUS_MATCH");});
