"use strict";

function prompt(task, credential) {
  const mode = task.mode === 'PRACTICE' ? 'Practice' : 'Pro Creation';
  return `Continue the ${mode} edit. Resume existing assignment ${task.assignmentId} and session ${task.sessionId}; do not create or restart the assignment. Keep After Effects open. Use only the provided raw footage and raw audio. ${mode === 'Practice' ? 'Finished is visual reference only.' : 'Use the designed target and actual render review.'}
Your exclusive worker credential is ${credential}. Use it as claimed_by or researchContext.claimedBy on this assignment. Copy the assignment ID from this prompt.
DIRECT_EDITING_V1: call claim_gpt_assignment once. Inspect its retained assignment, production jobs/receipts, production state, notebook, raw selections, checkpoint and aeState once. Resume from the current actual edit, not an earlier worker's task list. Current AE state and durable receipts establish what has changed; the user's goal and directly reviewed pixels establish what remains unfinished. A SUCCEEDED job alone is not visual acceptance. Honor an already completed, cancelled or explicitly paused assignment.
ChatGPT alone decides shots, audio, timing, framing, effects/transitions, exact settings/curves, the next useful action and final PASS/REVISE. Preserve correct retained work. Do not repeat completed discovery, construction, research, corrections or review just because an old note or phase label mentions them. Do not revert later work to an older checkpoint. Legacy stage labels and historical handoffs are context, not a current task backlog. Choose only the remaining work needed to finish; there is no fixed sequence to restart at each handoff. Reuse retained raw selections and reviewed notebook methods. Browse raw footage yourself when a selection is genuinely missing or needs correction; import selected working ranges rather than full raw movies. Research only an unfamiliar or changed component, using Tutorial Drive -> Adobe resources -> web.
Use the connected EditFlow - Current Shadow tools for this assignment. Resume once -> ChatGPT decides -> AE batch -> inspect -> correct is the sole workflow. There is no separate tool-inventory/preflight checklist, repeated ownership read, research-plan approval, workflow-plan gate, broad-edit declaration or per-shot PASS gate. Retired tool descriptions and historical workflow records do not add these gates. workflowContext and READY research plans are optional. No periodic research heartbeat is required to keep a processing chat authorized.
Submit exact operations via enqueue_production_job with kind AE_BATCH or AE_TRANSACTION, payload.researchContext={assignmentId,claimedBy,clipIds:[affected shots]} and payload.editorialDecision={authority:CHATGPT_DIRECT,decisionId,rationale,evidenceRefs,steps}. Batch coherent work, up to 64 exact AE actions per AE_BATCH. Prefer supported native intents; use opaque scripts only for genuinely unsupported operations. Routine enqueue calls return completion, readbacks, currentState and checkpoint. Read a retained job ID only for pending/uncertain work or a receipt needed to answer a current question; do not reread full history routinely. The queue journals receipts and saves an AEP checkpoint after committed batches. A known read-only rejection wrote nothing: correct that request. Reconcile partial/unknown writes before resolving or replaying them.
Render and inspect only what answers a current editing question: LOCAL_RENDER frameTimesMs for stills, or startMs/endMs for motion/audio, then BROWSE_RENDER. Reuse a suitable unchanged preview or final render; render again when the edit changed or existing output cannot answer the question. Group related corrections before review. Completed previews do not require a separate resolve receipt. Final PASS requires direct audiovisual review of a current full-resolution whole-edit render. Save reviewed reusable methods and successes/failures in the preset notebook. Call complete_gpt_assignment only after final PASS, using the retained current render and final_review_json with authority CHATGPT_DIRECT, verdict PASS, renderJobId, renderSha256, remainingIssues [], checks and actual per-shot pixel comparisons. Report completion only after the successful assignment-completion receipt.
Keep working after research, web browsing, previews and progress reports until the assignment is complete or an actual unresolved failure prevents dependent work. On a read connection failure retry only that read after 2, 5 and 15 seconds. If needed, run the installed transport repair through Desktop Commander: powershell.exe -NoProfile -ExecutionPolicy Bypass -File "$env:LOCALAPPDATA\\EditFlow2\\chat-supervisor\\repair-transport.ps1" -AssignmentId "${task.assignmentId}" -Reason connector_unavailable. local.ready=true does not establish public availability: require public.ready=true and a successful Current Shadow read before dependent writes. If bounded repair fails, retain the exact pending job IDs and next action. Do not treat a transport outage as an editing approval/workflow gate or completion. Do not retry a timed-out write: inspect its durable receipt and actual state first. Report an actual host denial and stop dependent writes; never retry a host-denied request through another path. A STALE_WORKER response means stop dependent writes; never recover revoked credentials. No parallel controllers or native-script bypasses. Missing optional research/workflow records are not a blocker.`;
}
module.exports = { prompt };
