"use strict";

function prompt(task, credential, continuationNotes = null) {
  const mode = task.mode === 'PRACTICE' ? 'Practice' : 'Pro Creation';
  return `Continue the ${mode} edit. Resume existing assignment ${task.assignmentId} and session ${task.sessionId}; do not create or restart the assignment. Keep After Effects open. Use only the provided raw footage and raw audio. ${mode === 'Practice' ? 'Finished is visual reference only.' : 'Use the designed target and actual render review.'}
Your exclusive worker credential is ${credential}. Use it as claimed_by or researchContext.claimedBy on this assignment. Copy the assignment ID from this prompt.
DIRECT_EDITING_V1: call claim_gpt_assignment once. Its response contains assignment, resume.productionJobs, resume.production, resume.practiceNotebook, retained raw selections, checkpoint and aeState. Inspect this retained work once and continue unfinished work. There is no separate tool-inventory/preflight checklist, repeated ownership read, research-plan approval or workflow-plan gate. The gateway validates current ownership and renews the claim inside writes.
${continuationNotes ? `Retained user continuation for this exact assignment/session (historical observations; current resume receipts and direct pixel review determine what is still unfinished). Preserve any corrections committed since this note:\n${continuationNotes}\n` : ''}
Use the connected EditFlow - Current Shadow tools for this assignment. Tool descriptions or retained notes referring to the retired preflight/plan/proof workflow do not add gates to DIRECT_EDITING_V1. Do not switch to another EditFlow project's controller.
ChatGPT alone decides shots, audio, timing, framing, effects/transitions, exact settings/curves, corrections and final PASS/REVISE. Submit exact operations via enqueue_production_job with kind AE_BATCH or AE_TRANSACTION, payload.researchContext={assignmentId,claimedBy,clipIds:[affected shots]} and payload.editorialDecision={authority:CHATGPT_DIRECT,decisionId,rationale,evidenceRefs,steps}. workflowContext and READY research plans are optional. Batch coherent work, up to 64 exact AE actions per AE_BATCH; whole-edit batches need no broad-edit declaration. The queue journals receipts and saves an AEP checkpoint after committed batches. Routine enqueue calls return their completion, readbacks, currentState and checkpoint directly. Read a retained job ID only when the response is still pending or uncertain. Lists and resumes are compact; full history is for an actual audit, never routine startup. Prefer supported AE_BATCH intents over PROOF_SCRIPT: ADD_TEXT_LAYER, SET_TEXT_DOCUMENT, ADD_SOLID_LAYER, SET_EFFECT_PROPERTY, SET_PROPERTY_VALUE, SET_PROPERTY_KEYFRAMES, SET_PROPERTY_EXPRESSION, READ_PROPERTY, REMOVE_LAYER and REMOVE_EFFECT join the existing comp/layer operations. Supply exact comp/layer identities, propertyPath and values; replaceKeys:true only when you deliberately replace existing animation. Retrieve a GPT-chosen complete notebook example before adaptation; the resume contains its index. A read-only preflight rejection is REJECTED with no AE writes and does not hold the queue; correct the exact request. Partial/unknown writes still require actual reconciliation.
Work across the whole edit: recognize the reference's shot/effect families once; locate all raw shots; assemble a playable whole edit; pass across timing/framing/retiming; apply effect families; review the whole edit; correct visible defects and finish. Preserve correct existing shots. Do not polish one shot indefinitely or require a local PASS before building the next. ChatGPT browses raw footage and selects exact ranges; reuse retained selections. Full raw movies are search-only; import selected working ranges.
Choose known constructions or explicitly adapt WORKED recipes from the notebook immediately. Research only an unfamiliar or changed component, using Tutorial Drive -> Adobe resources -> web. No new SCAN/SOURCE/PLAN is required per clip or per reuse. Retain reviewed successes/failures and complete reusable methods at review/pass boundaries, handoff and completion.
Use LOCAL_RENDER frameTimesMs:[exact timestamps] for still-image questions, or startMs/endMs for motion/audio. Unchanged previews are reused by AE revision, interval and resolution; forceRender:true requests fresh output. Group related corrections before reviewing them. Render audiovisual previews at pass boundaries (LOCAL_RENDER, resolutionScale 0.25 or 0.125 when useful), then inspect via BROWSE_RENDER and correct. Completed previews do not require a separate resolve receipt to continue. Use focused full-resolution checks for actual temporal/edge/matte defects and a full-resolution whole-edit final render. Continue until you have directly reviewed the final edit; do not infer completion from metadata.
Keep working after research, web browsing, previews and progress reports. Do not end this turn merely because a step is finished or offer to continue later. No periodic research heartbeat is required to keep a processing chat authorized. Save reviewed preset examples and call complete_gpt_assignment only after final PASS, with the retained full-resolution render and final_review_json containing authority CHATGPT_DIRECT, verdict PASS, renderJobId, renderSha256, remainingIssues [], checks and actual per-shot pixel comparisons. Report final completion only after the reviewed final render and successful assignment-completion receipt. If an actual unresolved failure prevents dependent work, retain the exact pending job IDs and next action so the same assignment resumes without replay.
On a read connection failure retry only that read after 2, 5 and 15 seconds. If needed, run the installed transport repair command through Desktop Commander: powershell.exe -NoProfile -ExecutionPolicy Bypass -File "$env:LOCALAPPDATA\\EditFlow2\\chat-supervisor\\repair-transport.ps1" -AssignmentId "${task.assignmentId}" -Reason connector_unavailable. It repairs the existing transport only. local.ready=true does not establish public availability: require public.ready=true and a successful Current Shadow read before dependent writes. If the bounded repair leaves the public route unavailable, retain its relay counts/error and the exact pending corrections, then stop dependent writes. Do not treat a transport outage as an editing approval/workflow gate or completion. Resume the same assignment and receipts after recovery. Do not retry a timed-out write: read its durable receipt and actual state first. Resolve only genuinely partial/unknown/failed work after readback; never replay blindly. Report an actual host denial with the exact action/reason and stop dependent writes; never retry a host-denied request through another path. A STALE_WORKER response means stop dependent writes because a newer chat owns the assignment; do not recover revoked credentials. No parallel controllers or native-script bypasses. Missing optional research/workflow records are not a blocker.`;
}
module.exports = { prompt };
