param([string]$AfterFxPath="C:\Program Files\Adobe\Adobe After Effects 2025\Support Files\AfterFX.exe",[int]$ProofTimeoutSeconds=35)
$ErrorActionPreference="Stop"
$root=(Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path;$config=Join-Path $env:LOCALAPPDATA "EditFlow2\bridge-config.json";$artifactRoot=Join-Path $root "proofs\artifacts\m3-human-parity-exit-gate-p5";$runId=(Get-Date -Format "yyyyMMdd-HHmmssfff")+"-"+[Guid]::NewGuid().ToString("N").Substring(0,8);$dir=Join-Path $artifactRoot ("run-"+$runId)
$result=Join-Path $dir "result.json";$ready=Join-Path $dir "broker-ready.json";$stdout=Join-Path $dir "node.stdout.log";$stderr=Join-Path $dir "node.stderr.log";$reopenScript=Join-Path $dir "reopen-proof.jsx";$cleanupScript=Join-Path $dir "cleanup-proof.jsx";$cleanupMarker=Join-Path $dir "cleanup-result.txt"
$preclean=Join-Path $root "scripts\windows\cleanup-m3-human-parity-exit-gate.jsx";$verify=Join-Path $root "scripts\windows\verify-blank-unsaved-ae.jsx";$opener=Join-Path $root "scripts\windows\open-editflow2-panel.jsx";$arm=Join-Path $root "scripts\windows\arm-m3-human-parity-exit-gate-p5-proof.jsx";$disarm=Join-Path $root "scripts\windows\disarm-m3-human-parity-exit-gate-p5-proof.jsx";$cli=Join-Path $root "scripts\m3-human-parity-exit-gate-p5.mjs"
$precleanEv=Join-Path $env:TEMP "EditFlow2-m3-exit-gate-cleanup.txt";$verifyEv=Join-Path $env:TEMP "EditFlow2-blank-unsaved-proof.txt";$armEv=Join-Path $env:TEMP "EditFlow2-m3-exit-p5-arm.txt";$disarmEv=Join-Path $env:TEMP "EditFlow2-m3-exit-p5-disarm.txt";$exit=1;$node=$null;$start=Get-Date
function Ae([string]$script,[string]$ev,[string]$prefix,[int]$seconds=4){if(Test-Path $ev){Remove-Item $ev -Force};[void](Start-Process -FilePath $AfterFxPath -ArgumentList @("-r",$script)-PassThru);$d=(Get-Date).AddSeconds($seconds);while((Get-Date)-lt $d){if(Test-Path $ev){$v=(Get-Content $ev -Raw).Trim();if($v.StartsWith($prefix,[StringComparison]::Ordinal)){return $v};throw "AE helper '$script' returned '$v'."};Start-Sleep -Milliseconds 50};throw "AE helper '$script' timed out."}
function PanelConnected(){try{$c=Get-Content $config -Raw|ConvertFrom-Json;$h=@{"X-EditFlow-Token"=[string]$c.token};$s=Invoke-RestMethod -Method Get -Uri ("http://127.0.0.1:{0}/v1/status"-f[int]$c.port) -Headers $h -TimeoutSec 1;return $s.panelConnected -eq $true}catch{return $false}}
function Recover(){if(Test-Path $cleanupScript){try{if(Test-Path $cleanupMarker){Remove-Item $cleanupMarker -Force};[void](Start-Process -FilePath $AfterFxPath -ArgumentList @("-r",$cleanupScript)-PassThru);$d=(Get-Date).AddSeconds(5);while((Get-Date)-lt $d){if(Test-Path $cleanupMarker){$v=(Get-Content $cleanupMarker -Raw).Trim();Write-Host "Dynamic P5 recovery: $v";if($v.StartsWith("OK|")){return};break};Start-Sleep -Milliseconds 50}}catch{Write-Host "Dynamic P5 recovery failed: $($_.Exception.Message)"}};try{$v=Ae $preclean $precleanEv "CLEANED ";Write-Host "Namespace recovery: $v"}catch{Write-Host "Namespace recovery failed: $($_.Exception.Message)"}}
try{
  New-Item -ItemType Directory -Force -Path $dir|Out-Null;foreach($p in @($AfterFxPath,$config,$preclean,$verify,$opener,$arm,$disarm,$cli)){if(-not(Test-Path $p -PathType Leaf)){throw "Required P5 path missing: $p"}}
  $running=@(Get-Process -Name AfterFX -ErrorAction SilentlyContinue|Where-Object{$_.Responding});if($running.Count -ne 1){throw "P5 requires exactly one responsive warm AE process; found $($running.Count)"}
  $pre=Ae $preclean $precleanEv "CLEANED ";$blank=Ae $verify $verifyEv "BLANK_UNSAVED";$armed=Ae $arm $armEv "ARMED";Write-Host "Exit-gate P5 preflight: $pre; $blank; $armed"
  Push-Location $root
  try{if(-not(Test-Path (Join-Path $root "node_modules"))){npm install;if($LASTEXITCODE -ne 0){throw "npm install failed"}};npm run build:test-runtime;if($LASTEXITCODE -ne 0){throw "runtime build failed"}
    $quotedAfterFx='"'+$AfterFxPath+'"';$args=@($cli,"--config",$config,"--result",$result,"--afterfx-path",$quotedAfterFx,"--broker-ready",$ready);$node=Start-Process -FilePath node -ArgumentList $args -NoNewWindow -PassThru -RedirectStandardOutput $stdout -RedirectStandardError $stderr
    $d=(Get-Date).AddSeconds(5);while((Get-Date)-lt $d -and -not(Test-Path $ready)){$node.Refresh();if($node.HasExited){break};Start-Sleep -Milliseconds 50};if(-not(Test-Path $ready)){if(Test-Path $stderr){Get-Content $stderr -Tail 100|Write-Host};throw "P5 broker did not become ready"}
    $d=(Get-Date).AddMilliseconds(900);while((Get-Date)-lt $d -and -not(PanelConnected)){Start-Sleep -Milliseconds 50};if(-not(PanelConnected)){[void](Start-Process -FilePath $AfterFxPath -ArgumentList @("-r",$opener)-PassThru);Write-Host "Opened EditFlow panel for P5 broker"}else{Write-Host "Warm EditFlow panel reconnected automatically for P5"}
    if(-not $node.WaitForExit($ProofTimeoutSeconds*1000)){Stop-Process -Id $node.Id -Force -ErrorAction SilentlyContinue;Start-Sleep -Milliseconds 500;throw "P5 core exceeded $ProofTimeoutSeconds seconds"};$node.WaitForExit();$node.Refresh();if(-not(Test-Path $result)){if(Test-Path $stderr){Get-Content $stderr -Tail 100|Write-Host};throw "P5 core emitted no machine result"}
  }finally{Pop-Location}
  $r=Get-Content $result -Raw|ConvertFrom-Json;if($r.ok -ne $true){Get-Content $result -Raw|Write-Host;throw ("P5 core machine result failed: "+[string]$r.failure)}
  $blankAfter=Ae $verify $verifyEv "BLANK_UNSAVED";$elapsed=[int]((Get-Date)-$start).TotalMilliseconds;$ok=$r.proofLevels.P5_transfer -eq $true -and $r.cleanupComplete -eq $true -and $blankAfter -eq "BLANK_UNSAVED";Write-Host "M3 exit-gate P5 result: ok=$ok coreMs=$($r.elapsedMs) wrapperMs=$elapsed speedTargetMet=$($r.speedTargetMet)";Get-Content $result -Raw|Write-Host;$exit=if($ok){0}else{1}
}catch{$message=$_.Exception.Message;Recover;Write-Error $message -ErrorAction Continue;$exit=1}
finally{try{$d=Ae $disarm $disarmEv "DISARMED";Write-Host "Exit-gate P5 gate: $d"}catch{Write-Error ("CRITICAL exit-gate P5 disarm failure: "+$_.Exception.Message) -ErrorAction Continue;$exit=1};if($node){try{$node.Refresh();if(-not $node.HasExited){Stop-Process -Id $node.Id -Force -ErrorAction SilentlyContinue}}catch{}}}
exit $exit
